version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www
        working_dir: /var/www
        expose:
            - "9000"  # PHP-FPM port
        depends_on:
            rabbitmq:
                condition: service_healthy

        networks:
            - shared-rabbit
            - laravel

    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        ports:
            - "8000:80"  # expose to your machine
        volumes:
            - .:/var/www
            - ./docker/nginx/laravel.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        container_name: laravel_mysql
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        healthcheck:
            test: ["CMD", "rabbitmqctl", "status"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - shared-rabbit

volumes:
    mysql_data:

networks:
    laravel:
        driver: bridge

    shared-rabbit:
        external: true
